spring.application.name=shoe-store
DB_URL=jdbc:mysql://localhost:3306/shoe
DB_USERNAME=springstudent
DB_PASSWORD=springstudent
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
